# Site settings
title: MK2016
email: madeleine.bonsma@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Madeleine and Kent's wedding website

baseurl: "/wedding" # the subpath of your site, e.g. /blog/
url: http://mbonsma.github.io # the base hostname & protocol for your site
twitter_username: mbonsma
github_username:  mbonsma

# Build settings
markdown: kramdown
